# Generated by Django 5.1.6 on 2026-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
    ]
